### ISSUE TITLE
Ability to exclude chosen folders

### ISSUE THREAD

**Issue by claremacrae** [ipshing/obsidian-broken-links#2]
_Disclaimer: I recently offered to help out with Dangling Links, as it hadn't been updated since May 2021. But you've implemented virtually all of the requested features in that plugin, so I will instead point requestors to this one!_ 🤣

As far as I can tell, the last feature that the previous [Dangling Links](https://github.com/graydon/obsidian-dangling-links) plugin has and this doesn't, is the ability to select one or more folders to be excluded.

For me, it's my templates folder. This is what the settings look like in that plugin, which offers a nice filtering/auto-suggest mechanism:

![image](https://github.com/ipshing/obsidian-broken-links/assets/4840096/c8c9d268-0cfc-4364-a54c-c176406eeeb5)

The workaround is to group by folder and collapse the folder - but then then 'Group by link' and 'Group by file' are still not useful.

For example, all but one of the remaining links shown in my main vault now are from templates:

<img width="761" alt="image" src="https://github.com/ipshing/obsidian-broken-links/assets/4840096/067aed11-9f47-497e-a09a-6b2a2f250ece">

**Comment by ipshing** [comment]
This is actually on my list of features to implement as I have a similar situation in my main vault. I'm holding off adding any new features until the plugin finishes the approval process but it's pretty much at the top of the queue.

**Comment by ipshing** [comment]
This feature has been added in version [1.1.0](https://github.com/ipshing/obsidian-broken-links/releases/tag/1.1.0) and is live in the Obsidian community plugins! Folder paths added to the ignore list should remove the folder and all its subfolders/files from appearing in the Broken Links panel.

**Comment by claremacrae** [comment]
Brilliant - thank you!
