### ISSUE TITLE
Is this a fork of dangling-links plugin?

### ISSUE THREAD

**Issue by xRyul** [ipshing/obsidian-broken-links#6]
Seems to do the same as dangling-links plugin.  
 
 At least in my vault it found exactly same files. And allows for the same filtering.

**Comment by ipshing** [comment]
This plugin was developed independently and is not a fork.

**Comment by claremacrae** [comment]
> Seems to do the same as dangling-links plugin.
> 
> At least in my vault it found exactly same files. And allows for the same filtering.

It's already better than Dangling Links. This already has a number of the capabilities that were requested in Dangling Links but had not yet been implemented, like finding links to missing headings.
